### ISSUE TITLE
Tinytex seems to be taking up a lot of space (453M) in Xournal++.

### ISSUE THREAD

**Issue by sabriunal** [flathub/com.github.xournalpp.xournalpp#99]
Tinytex seems to be taking up a lot of space (453M) in Xournal++.

Is there any way to reduce the package size by removing irrelevant files?

How to test:
```shell
flatpak run --devel --command=sh com.github.xournalpp.xournalpp
cd /app/
du -h
```
[xournal++.log](https://github.com/flathub/com.github.xournalpp.xournalpp/files/14303807/xournal%2B%2B.log)

**Comment by rolandlo** [comment]
You can also sort by size, `du -h * | sort -h`. About half of the space is taken by fonts. 

It would be nice to bring down the size of tinytex. We have a smaller tinytex size for the snap package (total size of the snap package for the stable version is 117 MB). The snap package's tinytex is based on a minimal base install, where packages are installed from a list of package names via `tlmgr`, see https://github.com/kenvandine/xournalpp/blob/stable/snapcraft.yaml#L124-L145.

It's not so easy for the flatpak, since LaTeX packages can't be installed like that. You have to specify the sources for all packages and install them manually, see https://github.com/flathub/com.github.xournalpp.xournalpp/blob/master/com.github.xournalpp.xournalpp.yaml#L204-L232. Flatpak doesn't allow internet access during installation in contrast to Snap. So we start with a larger install (TinyTeX-v2023.10.tar.gz is 207 MB compressed) and only install two more packages, for which there are stable links. There is stuff in there, that isn't really necessary, but if we start with a smaller base, we have to specify a lot of additional package sources and install them from hand.

We do actually remove some files (the documentation files), which are irrelevant for running pdflatex or friends. I don't know if it would be appropriate to just delete some fonts.

**Comment by rolandlo** [comment]
Thinking about it, I have found an idea how we could bring down the size of TinyTex:
There is a list of package that are installed via the TinyTeX version we install for the flatpak:
https://github.com/rstudio/tinytex/blob/main/tools/pkgs-yihui.txt
We also have the list of packages that we use for the snap package:
https://github.com/kenvandine/xournalpp/blob/stable/pkgs-custom.txt

We could probably simply remove all packages from the first list which are not in the second list via `tlmgr remove <pkglist>`. That doesn't need internet access, I think.

**Comment by rolandlo** [comment]
Looks like I brought the size down from 484 MB to 218 MB. I will create a PR soon. Hope it works.
